---
#Execute the below ONTAP Role after Nexus playbook
- name: Configure ONTAP for FlexPod Base Setup
  hosts: ontap
  gather_facts: False
  vars_files:
    - group_vars/secrets.yml
    - group_vars/all.yml
    - vars/ontap_main.yml
  connection: local
  roles:
  - { role: ONTAP/ontap_primary_setup, tags: [ 'ontap_primary_setup' ] }
  - { role: ONTAP/ontap_network, tags: [ 'ontap_network' ] }
  tags:
  - ontap_base_config
  - flexpod_base_config
