---
  # This Task enables Features required for setting up FC configuration

  - name: Enable Features
    cisco.nxos.nxos_feature:
      feature: "{{ item }}"
      state: enabled
    with_items: "{{ enabled_mds_features }}"
