---
- name: "Create Link Control UDLD Policy"
  vars:
    api_info: &api_info_udld
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  cisco.intersight.intersight_rest_api:
      <<: *api_info_udld
      resource_path: /fabric/LinkControlPolicies
      query_params:
         $filter: "Name eq '{{ name_of_udld_policy }}'"
      api_body: {
        "Name": "{{ name_of_udld_policy }}",
        "Description": "{{ description_of_udld_policy }}",

        "Organization": {
           "Moid": "{{ intersight_org.api_response.Moid }}"
         },
        Tags: [{Key: "configmode", Value: "ansible"},{Key: "prefix", Value: "{{ prefix }}"}],
        "UdldSettings": {
		      "AdminState": "Enabled",
		      "Mode": "normal"
	      }
      }
  register: udld_policy
