---
- name: "Create Multicast Policy"
  vars:
    api_info: &api_info_multicast
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  cisco.intersight.intersight_rest_api:
      <<: *api_info_multicast
      resource_path: /fabric/MulticastPolicies
      query_params:
         $filter: "Name eq '{{ name_of_multicast_policy }}'"
      api_body: {
        "Name": "{{ name_of_multicast_policy }}",
        "Description": "{{ description_of_multicast_policy }}",

        "Organization": {
           "Moid": "{{ intersight_org.api_response.Moid }}"
         },
        Tags: [{Key: "configmode", Value: "ansible"},{Key: "prefix", Value: "{{ prefix }}"}],
        "QuerierState": "Disabled",
        "SnoopingState": "Enabled",
        "SrcIpProxy": "Enabled"
       }
  register: multicast_policy
