---
# Variables defined here are specific to Nexus9K-B for SAN Switching.
#
# Variables used to create port channel to UCS.
  port_channel_id: 1103
  port_channel_speed: "auto" # Set to "auto" for FCoE port-channel and either "16000" or "32000" for FC port-channel
  port_channel_duplex: "auto"
  port_channel_description: "AA02-6536-B"
#
#  VSAN number to use used for a the fabric being created
  vsan_id: "{{ vsan_B_id }}"
  vsan_name: "{{ vsan_B_name }}"
#
# Nexus Switch Interface List
#
  storage_interface_list:
    - interface: "fc1/1"
      description: "AA02-C800-01:2b"
      speed: "32000"
    - interface: "fc1/2"
      description: "AA02-C800-01:2d"
      speed: "32000"
    - interface: "fc1/49"
      description: "AA02-C800-02:2b"
      speed: "32000"
    - interface: "fc1/50"
      description: "AA02-C800-02:2d"
      speed: "32000"
# Comment out the interfaces not being used below.
  ucs_interface_list:
#    - interface: "fc1/3"
#      description: "AA02-6536-B:fc1/35/1"
#    - interface: "fc1/4"
#      description: "AA02-6536-B:fc1/35/2"
#    - interface: "fc1/51"
#      description: "AA02-6536-B:fc1/35/3"
#    - interface: "fc1/52"
#      description: "AA02-6536-B:fc1/35/4"
    - interface: "Eth1/103"
      description: "AA02-6536-B:Eth1/27"
    - interface: "Eth1/104"
      description: "AA02-6536-B:Eth1/28"
